server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://132.232.11.223:3306/guli_sms
    username: test
    password: test
  redis:
    host: 132.232.11.223
  cloud:
    nacos:
      discovery:
        server-addr: 132.232.11.223
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:mapper/**/*.xml