server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 132.232.11.223:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://132.232.11.223:3306/guli_pms
    username: test
    password: test
  redis:
    host: 132.232.11.223
    #    port:

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:mapper/pms/**/*.xml